[package]
name = "frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
shared = { version = "3.3.106", path = "../shared" }
chrono.workspace = true
yew = "0.23.0"
yew-router = "0.20.0"
yew-hooks = "0.6.4"
i18nrs = "0.1.9"
serde_json.workspace = true
serde.workspace = true
wasm-bindgen = {version = "0.2.127", features = ["serde-serialize"]}
#anyhow = "1.0.102"
thiserror = "2.0.20"
gloo-net = { version = "0.5.0", default-features = false, features = ["http", "json"] }
log.workspace = true
wasm-logger = "0.2.0"
gloo-storage = "0.3.0"
gloo-utils = "0.2.0"
#gloo-render = "0.2.0"
gloo-timers = { version = "0", features = ["futures"] }
#implicit-clone = "0.6.0"
futures-signals = "0.3.34"
futures.workspace = true
wasm-bindgen-futures = "0.4.77"
js-sys = "0.3.104"
bytes.workspace = true
regex.workspace = true
base64.workspace = true
cron.workspace = true
fastrand.workspace = true
indexmap.workspace = true
strum.workspace = true
strum_macros.workspace = true

[dependencies.web-sys]
version = "0.3.104"
features = ["AbortController", "AbortSignal", "ReadableStream", "ReadableStreamDefaultReader", "Document", "Element", "Node", "Window", "HtmlCollection", "HtmlImageElement", "HtmlInputElement", "DomRect", "HtmlDialogElement", "CssStyleDeclaration", "Event", "BeforeUnloadEvent", "MutationObserver", "MutationObserverInit", "WebGlRenderingContext", "WebGlProgram", "WebGlShader", "WebGlBuffer", "WebGlUniformLocation", "HtmlCanvasElement", "HtmlSelectElement", "DomTokenList", "Selection"]

[dev-dependencies]
wasm-bindgen-test = "0.3.77"
gloo-utils = "0.2.0"
